version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: cli
    main: ./cmd/vmstats/main.go
    binary: vmstats
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
    goarch:
      - amd64
      - arm64
      - "386"
      - arm
    ignore:
      - goos: windows
        goarch: arm
    ldflags:
      - -s -w
      - -X github.com/crazyuploader/vmstats/internal/version.Version={{.Version}}
      - -X github.com/crazyuploader/vmstats/internal/version.GitCommit={{.FullCommit}}
      - -X github.com/crazyuploader/vmstats/internal/version.BuildDate={{.Date}}
    flags:
      - -trimpath

archives:
  - id: cli
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{- title .Os }}_{{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip

homebrew_casks:
  - repository:
      owner: crazyuploader
      name: homebrew-tools
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    name: vmstats
    homepage: "https://github.com/crazyuploader/vmstats"
    description: "Beautiful terminal UI for monitoring libvirt/KVM virtual machine statistics"
    license: "MIT"
    binaries:
      - vmstats

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ .Version }}-SNAPSHOT-{{.ShortCommit}}"

release:
  footer: |-
    ---

    **Full Changelog**: {{ .GitURL }}/compare/{{ .PreviousTag }}...{{ .Tag }}

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
